const data = [
  "Secure Mode",
  "Advance Purchase of Airport and Pier Transportation",
  "Age Restrictions On Board Answer",
  "Alternate Telephone Numbers Answer",
  "American Table and American Feast Answer",
  "Autism (B) ",
  "Automatic Teller Machines (ATM) ",
  "Balcony Stateroom Information ",
  "Bed Dimensions ",
  "Booking Takeover Policy ",
  "Bottomless Bubbles (Unlimited Soda Program) ",
  "Call Center Telephone Extension List ",
  "Calling Home ",
  "Camp Ocean Night Owls ",
  "Cancellation Penalties and Refunds ",
  "Carnival Gift Card Program ",
  "Carnival LIVE Concert Series ",
  "Carnival Vacation Protection (VPP) ",
  "Carnival Vacation Protection (VPP) Answer",
  "Carnival's Future Cruise Vacation Program ",
  "Carnival's Wi-Fi Service and HUB App ",
  "Carnival's Youth Program ",
  "Carnivals Great Vacation Guarantee ",
  "Carnivals Seuss at Sea Program ",
  "Cash Advance on Credit Cards and Debit Cards ",
  "CashPro Biller ",
  "Celebrating Holidays ",
  "Cellular Phone Service ",
  "Check Cashing / Travelers Checks ",
  "CHEERS! Beverage Program ",
  "Children with Disabilities ",
  "Cloud 9 Spa ",
  "Commission for Travel Agency Bookings ",
  "Credit Card Gift Cards | Carnival Gift Cards ",
  "Criminal Records (guest with) ",
  "Criminal Records (guest with) - entry into Canada ",
  "Cruise Dollars Scrip Dollars ",
  "Cuba - Everything You Need to Know Before Cruising  ",
  "Cuba - Travel to Cuba - Travel Affidavit  ",
  "Cuba Travel to Cuba Announcement 100217  ",
  "Cuba - Travel to Cuba Q&A ",
  "Cuba - Travel to Cuba Sales Script and Additional Q&As ",
  "Cuba Checklist ",
  "Currency Exchange ",
  "Deaf (J) ",
  "Deck Parties ",
  "Deposit and Final Payment Requirements ",
  "Diabetic (D) | Sharps Container (R) ",
  "Dialysis (S) ",
  "Dining Room Open Seating Breakfast / Brunch / Lunch ",
  "Direct Consumer / Verifying the PIN (Qualifying the Caller) ",
  "Direct Customers Booked Through a Travel Agency ",
  "Duty Free Allowance ",
  "Early Saver and Early Saver Last Call Promotion ",
  "Early Saver Program ",
  "Elegant Evening --- What to Wear - Evenings ",
  "Embarkation - Luggage Information ",
  "Entertainment and Activities ",
  "Faster to the Fun (FTTF) ",
  "Fitness Classes / Fitness and Beauty Seminars ",
  "Fly2Fun Air City Codes ",
  "Fly2Fun Program Guarantee ",
  "Fly 2 Fun Presentation ",
  "For Your Eating Pleasure... ",
  "Fun by Home Port ",
  "Fun by Ports-of-Call ",
  "Funship Dollars Gift Certificates (ended Dec 2012) ",
  "Funship Features ",
  "Fun Shops Gift Orders ",
  "Future Cruise Credits (FCC) - Redeem and Transfer ",
  "Guest Access General Information ",
  "Guest Comment Codes ",
  "Guest Emergency Call Form ",
  "Guest Names on a Booking ",
  "Guest Profile in Navi iKnow / Forms Guest Recognition - Milestone Rewards Program ",
  "Guys! Burger Joint ",
  "Holding a Reservation Name Policy / Deposit Policy ",
  "How to book a Wedding Package ",
  "Indian Meals ",
  "Infant Policy ",
  "Interline Program ",
  "Kosher Meals ",
  "Liquor and Beverage Policy ",
  "Lowest Price Guarantee ",
  "Marijuana (Carnival Prohibited Items ) ",
  "Military Discount Rate ",
  "Minor Guest Policy ",
  "Multi-Currency Payment ",
  "Nightclubs ",
  "Non-Commission Fares Taxes, Fees & Port Expenses ",
  "Non-Stocked Mini Bar Unit ",
  "Online Check-In, How to Access ",
  "Online Check-In, How to Complete ",
  "Other Medical (U) also for CPAP ",
  "Oxygen (Z) ",
  "Past Guest Promotion ",
  "Pixels Photo Gallery and Dreams Studio ",
  "Policy on Transgender Guests/Cross Dressing ",
  "Post Booking Sales (PBS) - (Upgrades) ",
  "Pregnancy Policy (Q) ",
  "Prohibited Items ",
  "Promo Quick Reference ",
  "Promo Re-Pricing Guidelines ",
  "Resident Rate ",
  "Resident Rate International (Canada) ",
  "Room Service - 24 hrs ",
  "Sail & Sign Onboard Account ",
  "Sample Indoor Bar Menu ",
  "Sample Outdoor Bar Menu ",
  "Senior Citizens Promotion ",
  "Serenity Adult Only Retreat ",
  "Service Charge (Admin Fee) ",
  "Service Gratuities (Tips) ",
  "Single Guest Programs ",
  "Shore Excursion FAQs ",
  "Shore Excursion Pre-Sail Information ",
  "Spa Prices ",
  "Spa Carnival - Time to Spa ",
  "Special Dietary Requirements and Food Items ",
  "Specialty Restaurants - Dining Reservation Information ",
  "Spoilage / Stateroom Occupancy Restrictions ",
  "Spoilage Policy / Occupancy Restrictions ",
  "Stateroom Spoilage Policy / Occupancy Restrictions ",
  "Steakhouse Selections in the Main Dining Room ",
  "Suite Amenities and Perks ",
  "TA Profile Change ",
  "Targeted Offers 'Travel with Bookings' ",
  "TBA Cabin Assignment Policy ",
  "The Fun Shops Gift Orders ",
  "The Steakhouse ",
  "Travel Agency Bookings / Verifying the Travel Agency ",
  "Travel Documentation U.S. Permanent Residents ",
  "Travel Documentation: Canadian Citizens ",
  "Travel Documentation: Non-U.S. Citizens ",
  "Travel Documentation: U.S. Citizens ",
  "Travel to Cuba Q&A (currency) ",
  "Vacation Protection - Hurricane Season ",
  "Vacation Protection Improved Features ",
  "VIFP Club - Carnival's Recognition Program ",
  "VIFP Club Member Sail & Sign Cards ",
  "Waitlist Bookings ",
  "What Does the Price of my Cruise Include? ",
  "What to Pack ",
  "What to Wear - Daytime ",
  "What to Wear - Evenings ",
  "Wheelchairs/Scooters/Segways (W) - Personal Mobility Devices ",
  "WLCL ",
  "WLCL phone #s ",
  "Working Service Dogs (5) ",
  "ZSPA for Teens ",
];

export default data;
